### ISSUE TITLE
Specify colors for filetypes

### ISSUE THREAD

**Issue by Shatur** [lambdalisue/fern-renderer-devicons.vim#4]
Is there a was to set colors for specific filetypes?
Something like `call NERDTreeHighlightFile('jade', 'green', 'none', 'green', '#151515')` as in [NERDTree](https://github.com/ryanoasis/vim-devicons/blob/028673dc93a978225c897b4913dd21b48dc35a7e/doc/webdevicons.txt#L871).

**Comment by lambdalisue** [comment]
Unfortunately no.

**Comment by Shatur** [comment]
Will this planned in the future? (Can I leave this issue open?)

**Comment by lambdalisue** [comment]
Not really by myself but PRs are welcome 👍 

You may need to rewrite

https://github.com/lambdalisue/fern-renderer-devicons.vim/blob/master/autoload/fern/renderer/devicons.vim#L34-L43

**Comment by Shatur** [comment]
Should I provide a function to highlight filenames? Or this should be a dictionary?

**Comment by lambdalisue** [comment]
I don't get the question. Could you explain the context a bit more?

**Comment by Shatur** [comment]
Sorry for my bad English. I meant how to provide an API for users to let them specify colors? Via function that accepts filename and color or via dictionary variable with filetypes and colors?

**Comment by lambdalisue** [comment]
Thanks, now I got it. Well, I don't have a strong preference for that but "via dictionary variable" sounds clean and simple 👍

**Comment by Shatur** [comment]
I found the best way! Devicons colors can be set globally: https://github.com/ryanoasis/vim-devicons/issues/158.
I tested, it works, but I need to undo [s:syntax()](https://github.com/lambdalisue/fern-renderer-devicons.vim/blob/master/autoload/fern/renderer/devicons.vim#L34-L43). Currently I just commented it out. Can I add an option to disable this function? Ideally it would be nice to leave filename highlighted for folders (to differentiate it from files) and remove all highlighting from icons.

**Comment by lambdalisue** [comment]
Cool. Yes, please. Additionally, it would be nice if the explanation about how to enable colors on devicons is written in somewhere in the docs.

**Comment by Shatur** [comment]
I separated highlighting groups:

```vim
syntax match FernLeaf /^\s*[^\x00-\x7F]/ nextgroup=FernBranch " Corresponds to icon
syntax match FernBranch /\s*.*\/$/ contained
syntax match FernRoot /\%1l.*/
```

And all I need is just disable highlighting for `FernLeaf` group. But this can be done only in main Fern module. So, can I add the option to disable this group highlighting in main Fern plugin instead?

I also tried to `:highlight clear FernLeaf` but this not works because this groups added dynamically. Another solution is define this groups at startup and user will can simply override or remove this just using `:highlight` command (a separate option will not be needed). What do you think?

**Comment by lambdalisue** [comment]
It's kind an inheritance so you can overwrite `highlight()` method like

```vim
function! fern#renderer#devicons#new() abort
  let default = fern#renderer#default#new()
  if !exists('*WebDevIconsGetFileTypeSymbol')
    call fern#logger#error("WebDevIconsGetFileTypeSymbol is not found. 'devicons' renderer requires 'ryanoasis/vim-devicons'.")
    return default
  endif
  return extend(copy(default), {
        \ 'render': funcref('s:render'),
        \ 'syntax': funcref('s:syntax'),
        \ 'highlight': funcref('s:highlight'),
        \})
endfunction

function! s:highlight() abort
  highlight default link FernRoot   Directory
  highlight clear FernLeaf " may require 'silent!'?
  highlight default link FernBranch Directory
  highlight default link FernMarked Title
endfunction
```

Or am I missing some point?

**Comment by Shatur** [comment]
> It's kind an inheritance so you can overwrite highlight() method like

Did not know about it :) Just what I need.

**Comment by lambdalisue** [comment]
Finally, I've made the following plugins to easily enable colors on fern.vim.

https://github.com/lambdalisue/nerdfont.vim
https://github.com/lambdalisue/glyph-palette.vim
https://github.com/lambdalisue/fern-renderer-nerdfont.vim

fern.vim with above plugins provide UI like below

![tmux 2020-07-29 01-52-18](https://user-images.githubusercontent.com/546312/88704120-9ec85100-d148-11ea-84c0-11730043a267.png)

In favor of the above, this plugin has deprecated.

Thanks for your recommendations and supports. All the above works are thanks to your supports @Shatur95

**Comment by Shatur** [comment]
Thank you! Will use your solution.

**Comment by Shatur** [comment]
I like the idea to use vim-devicons without integrations with unneeded plugins, but the only one thing I missing is the icons in `vim-lightline` :( Maybe just add an option in `fern-renderer-nerdfont.vim` to use vim-devicons? Or maybe I can integrate it somehow? `vim-lightline` have the same spirit as your `nerdfont.vim`.

**Comment by lambdalisue** [comment]
*fern* or *fern-renderer-nerdfont* should NOT care about non related plugins such as *lightline* so

1. Create *vim-lightline-nerdfont* which add icons on *lightline* through *nerdfont* (Recommended)
2. Add *vim-devicons* **for *lightline*** and keep using *fern-renderer-nerdfont/nerdfont* for *fern* (icon features are duplicated but should work)
3. Keep using *fern-renderer-devicons/vim-devicons* (*fern-renderer-devicons* is **deprecated** thus not recommended)

The *nerdfont* try to replace *vim-devicons* thus it provides required features to implement integration plugins. 
However, I cannot create all integrations by myself so I'm very happy if you decided to create *vim-lightline-nerdfont* or whatever.

**Comment by Shatur** [comment]
> Create vim-lightline-nerdfont which add icons on lightline through nerdfont (Recommended)

I will try this way :)

**Comment by Shatur** [comment]
Oh, I forgot that icons in vim-lightline was configured by myself :D The plugin do not have icons by default. So, no problem here.
But there is [vim-bufferline](https://github.com/mengelbrecht/lightline-bufferline) that hardcodes vim-devicons usage. I will send a PR to it to add a support for your plugin.
